### ISSUE TITLE
quote

### ISSUE THREAD

**Issue by nickalaskreynolds** [nickalaskreynolds/Star-Bot#8]
add an option
> quote previous

which just creates a quote of the most recently sent message in channel

**Comment by nickalaskreynolds** [comment]
allow
> quote Nick
to quote a random user command

**Comment by jacobcov** [comment]
Example text for "!quote top" says "quofte" instead of "quote"

**Comment by jacobcov** [comment]
Maybe consider putting the argumentless example first, then iterate upon that with arguments

**Comment by jacobcov** [comment]
Minor, but the explanatory text for the list and showall arguments don't start with a capital letter while the rest do

**Comment by nickalaskreynolds** [comment]
Completed all the above issues with the exception of could not determine why donna's yielded an error. Will have to do more testing on it later as the error arises. Closing for now

**Comment by nickalaskreynolds** [comment]
quote previous failed. It has to do with the resolve name from member 
```
java.lang.NullPointerException
	at io.ph.util.Util.resolveNameFromMember(Util.java:110)
	at io.ph.bot.commands.general.Quote.previousMsg(Quote.java:134)
	at io.ph.bot.commands.general.Quote.executeCommand(Quote.java:91)
	at io.ph.bot.commands.CommandHandler.lambda$processCommand$0(CommandHandler.java:98)
	at io.ph.util.Util.lambda$setTimeout$0(Util.java:339)
	at java.base/java.lang.Thread.run(Thread.java:844)```

**Comment by nickalaskreynolds** [comment]
If a user leaves the server and isn't on any server the bot is in. When it tries to serve back the quote it will give an error.

So correction should be, search all shards for user or member. If not found then just reserve the given name/id. This issue might be combined or adjusted to new issue under a more generic title for better user handling.
